/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'bastiano' at '1/11/17 1:23 PM' with Gradle 2.9
 *
 * @author bastiano, @date 1/11/17 1:23 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
